language: node_js

node_js:
  - "6"
  - "8"

before_script:
  - npm install -g bower grunt-cli
  - bower install

script:
  - grunt linters test-unit-frontend test-unit-backend --chunk=1 --ci

# trigger the Travis build on linagora/openpaas-esn to build a new docker image
# with latest commit from this repo
deploy:
  provider: script
  script: scripts/trigger_travis.sh
  on:
    repo: linagora/linagora.esn.admin
    branch: master
    node: "6"
